version: '3.1'
services:

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
      - POSTGRES_DB=stats

  stats-server:
    container_name: stats
    build:
      context: ./stats
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - spring_datasource_username=stats
      - spring_datasource_password=stats

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5433"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=explorewithme
      - POSTGRES_PASSWORD=explorewithme
      - POSTGRES_DB=explorewithme

  ewm-service:
    ports:
      - "8080:8080"
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explorewithme
      - spring_datasource_username=explorewithme
      - spring_datasource_password=explorewithme
      - stats-app.url=http://stats:9090




#services:
#  stats-server:
#    ports:
#      - "9090:9090"
#
#  stats-db:
#    image: postgres:14-alpine
#
#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine