CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(255)                            not null,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat float,
    lon float,
    constraint pk_location primary key (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_id        bigint                                  not null references categories (id),
    user_id            bigint                                  not null references users (id),
    location_id        bigint                                  not null references locations (id),
    paid               bool,
    request_moderation bool,
    participant_limit  bigint,
    annotation         VARCHAR(255)                            NOT NULL,
    description        varchar(255)                            not null,
    confirmed_requests bigint,
    created_on         bool,
    published_on       bool,
    event_date         timestamp                               not null,
    CONSTRAINT pk_events PRIMARY KEY (id)
);











